### ISSUE TITLE
Problem after editing config.

### ISSUE THREAD

**Issue by thiagokenis** [Shnupbups/easyexcavate#2]
Hi, I'm having this error after editing the settings
https://pastebin.com/v5CvPYxv

Below is a link to view the config file
https://pastebin.com/9SP9U52S
Thank you!

**Comment by thiagokenis** [comment]
> Hi, I'm having this error after editing the settings
> https://pastebin.com/v5CvPYxv
> 
> Below is a link to view the config file
> https://pastebin.com/9SP9U52S
> Thank you!

 I discovered what was wrong, the config file.

https://pastebin.com/Hyx0N43U

 

The game is no longer giving error, but the configuration is not working.

**Comment by Shnupbups** [comment]
The correct configuration would be this:
https://pastebin.com/3SHL6gBG
I'll try to make this more clear in the next update.
