### ISSUE TITLE
just dosent work

### ISSUE THREAD

**Issue by egg22** [Shnupbups/easyexcavate#6]
it dosent clear tree logs or lumps of ore it doesnt do anything

**Comment by Shnupbups** [comment]
Please give more information.

What version of the mod are you using, what version of Minecraft, what version of Fabric API, what version of Fabric Loader, what are your config settings set to, what is your excavate key set to, are you actually holding the key, what tool are you using...

I can't help if you just say "it doesn't work".

**Comment by egg22** [comment]
fabric loader 0.4.8 build 159 for 1.14.4
i just used the version 1.5.1

**Comment by egg22** [comment]
wait il redownload it i think i got an older version

**Comment by egg22** [comment]
it still dosent work
