### ISSUE TITLE
Crashes Game

### ISSUE THREAD

**Issue by Lobituki** [Shnupbups/easyexcavate#8]
So when I try to excavate things, it entirely crashes my game; pretty much ONLY when I get to the block's breaking point.. I have NO idea how to fix this, how it's happening, etc.. here's the error log.

https://gist.githubusercontent.com/natanfudge/1dc7e7468cc18f59343e112d888a70d7/raw/55334010a39de3bf8c8c4e1e29dc24208b1193f0/crash.txt

**Comment by Shnupbups** [comment]
this mod has been abandoned for ages what are you doing
